[mypy]
python_version = 3.11
warn_return_any = False
mypy_path = .:..

[mypy-psutil]
ignore_missing_imports = True

[mypy-guitarpro]
ignore_missing_imports = True

[mypy-pandas]
ignore_missing_imports = True

[mypy-pandas.*]
ignore_missing_imports = True
