#!/usr/bin/env python3
"""Export curated learn records into an Obsidian vault as navigable markdown notes.

Reads ``learn_engine/memory/lessons.jsonl`` (the curated store) and renders one
markdown note per lesson under ``memory/learn/patterns/``, plus generated
``index.md``, ``repos/<repo>.md`` and ``tags/<tag>.md`` navigation pages.

Design rules (Learn Export MVP):

* **One-way, read-only against the source.** The lessons store is never
  modified; this script only reads it.
* **Deterministic and idempotent.** The same input always renders the same
  bytes; unchanged files are not rewritten, so git/Obsidian diffs stay clean.
* **No reinterpretation.** Lessons are normalized, packaged and linked — never
  summarized, generalized or "improved". Missing fields get conservative
  fallbacks, not invented content.
* **Tag-driven thematic dimension.** ``lessons.jsonl`` has no ``pattern_type``
  field; the real thematic signal is the ``tags`` array, so the thematic
  navigation pages are ``tags/<tag>.md`` (a lesson appears under every tag it
  carries) rather than a fabricated single type.

Non-goals (MVP): no two-way sync, no automatic ``hot.md`` updates, no
promotion, no embeddings, no inbox export.

Usage::

    python scripts/export_learn_to_obsidian.py \
        --vault /Users/mansys/mqobsidian \
        --lessons /Users/mansys/mq-mcp/learn_engine/memory/lessons.jsonl

Add ``--dry-run`` to compute and report changes without writing anything.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

LEARN_SUBDIR = "memory/learn"

# repo -> vault note path (without extension) used for the "system" backlink.
# Only emitted when the target note actually exists in the vault, so the export
# never produces dead links for repos that have no system page yet.
SYSTEM_INDEX_MAP = {
    "mq-mcp": "systems/mq-mcp/index",
    "mq-agent": "systems/mq-agent/index",
    "mq-ums": "systems/mq-ums/index",
    "mq-hal": "systems/mq-hal/index",
    "mq-image-analyze": "systems/mq-image-analyze/index",
    "repo-signal": "mq-stack/repos/repo-signal",
    "mqobsidian": "mq-stack/repos/mqobsidian",
}

_GENERATED_BANNER = (
    "> Generated by `scripts/export_learn_to_obsidian.py`. Do not edit by hand — "
    "changes are overwritten on the next export."
)

_SLUG_RE = re.compile(r"[^A-Za-z0-9_-]+")


# ---------------------------------------------------------------------------
# Loading & normalization
# ---------------------------------------------------------------------------


def load_lessons(path: Path) -> tuple[list[dict[str, Any]], list[str]]:
    """Read and JSON-parse every non-blank line in ``lessons.jsonl``.

    Returns ``(lessons, errors)``. Unparseable lines are collected as error
    strings rather than aborting the whole export.
    """
    lessons: list[dict[str, Any]] = []
    errors: list[str] = []
    if not path.exists():
        errors.append(f"lessons file not found: {path}")
        return lessons, errors
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        line = raw.strip()
        if not line:
            continue
        try:
            obj = json.loads(line)
        except json.JSONDecodeError as exc:
            errors.append(f"line {lineno}: invalid JSON ({exc.msg})")
            continue
        if not isinstance(obj, dict):
            errors.append(f"line {lineno}: expected a JSON object")
            continue
        lessons.append(obj)
    return lessons, errors


def _slug(value: str) -> str:
    """Filesystem- and wikilink-safe slug, stable across runs.

    Lower-cased so that case-only variants (e.g. ``MD004`` / ``md004``) map to a
    single page. macOS filesystems are case-insensitive, so without this two
    such tags would collide on one file and silently drop a lesson.
    """
    slug = _SLUG_RE.sub("-", str(value or "").strip()).strip("-").lower()
    return slug or "unknown"


def _group_by_tag(lessons: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    """Group lessons by tag slug (case-insensitive).

    Returns ``slug -> {"display": <representative spelling>, "lessons": [...]}``.
    ``display`` is the lexicographically smallest original spelling, for stable
    output. A lesson carrying two case-variants of the same tag is counted once.
    """
    groups: dict[str, dict[str, Any]] = {}
    for lesson in lessons:
        for slug in dict.fromkeys(_slug(t) for t in lesson["tags"]):
            originals = [t for t in lesson["tags"] if _slug(t) == slug]
            group = groups.setdefault(slug, {"display": originals[0], "lessons": []})
            group["display"] = min(group["display"], *originals)
            group["lessons"].append(lesson)
    return groups


def normalize_lesson(raw: dict[str, Any]) -> dict[str, Any]:
    """Map a raw curated record into the canonical shape used for rendering.

    Conservative fallbacks only; no content is invented or reinterpreted.
    """
    lesson_text = str(raw.get("lesson") or raw.get("summary") or "").strip()
    tags_raw = raw.get("tags") or []
    tags = [str(t).strip() for t in tags_raw if str(t).strip()] or ["learn"]

    validation_raw = raw.get("validation")
    if isinstance(validation_raw, list):
        validation = [str(v).strip() for v in validation_raw if str(v).strip()]
    elif isinstance(validation_raw, str) and validation_raw.strip():
        validation = [validation_raw.strip()]
    else:
        validation = []

    def _list(key: str) -> list[str]:
        val = raw.get(key) or []
        if isinstance(val, str):
            val = [val]
        return [str(x).strip() for x in val if str(x).strip()]

    return {
        "id": str(raw.get("id") or "").strip(),
        "repo": str(raw.get("repo") or "unknown").strip() or "unknown",
        "risk": str(raw.get("risk") or "unknown").strip() or "unknown",
        "source": str(raw.get("source") or "unknown").strip() or "unknown",
        "stored_at": str(raw.get("created_at") or raw.get("stored_at") or "").strip(),
        "confidence": str(raw.get("confidence") or "").strip(),  # rarely present
        "lesson": lesson_text or "No lesson text stored.",
        "task": str(raw.get("task") or "").strip(),
        "problem": str(raw.get("problem") or "").strip(),
        "solution": str(raw.get("solution") or "").strip(),
        "validation": validation,
        "commands_used": _list("commands_used"),
        "files_touched": _list("files_touched"),
        "tags": tags,
    }


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _yaml_scalar(value: str) -> str:
    """Quote a YAML scalar if it could be misparsed; otherwise leave bare."""
    if value == "" or re.search(r"[:#\[\]{}&*!|>'\"%@`,]", value) or value != value.strip():
        return json.dumps(value)  # JSON strings are valid YAML double-quoted scalars
    return value


def render_lesson_markdown(lesson: dict[str, Any], vault_root: Path) -> str:
    """Render one normalized lesson into a complete markdown note."""
    repo = lesson["repo"]
    repo_slug = _slug(repo)

    related: list[str] = []
    system_target = SYSTEM_INDEX_MAP.get(repo)
    if system_target and (vault_root / f"{system_target}.md").exists():
        related.append(f"[[{system_target}]]")
    related.append(f"[[{LEARN_SUBDIR}/repos/{repo_slug}]]")
    related.extend(f"[[{LEARN_SUBDIR}/tags/{s}]]"
                   for s in dict.fromkeys(_slug(t) for t in lesson["tags"]))

    fm: list[str] = ["---"]
    fm.append(f"id: {_yaml_scalar(lesson['id'])}")
    fm.append(f"repo: {_yaml_scalar(repo)}")
    fm.append(f"risk: {_yaml_scalar(lesson['risk'])}")
    fm.append(f"source: {_yaml_scalar(lesson['source'])}")
    if lesson["confidence"]:
        fm.append(f"confidence: {_yaml_scalar(lesson['confidence'])}")
    if lesson["stored_at"]:
        fm.append(f"stored_at: {_yaml_scalar(lesson['stored_at'])}")
    fm.append("approved: true")
    fm.append("hot_candidate: false")
    fm.append("tags:")
    fm.extend(f"  - {_yaml_scalar(t)}" for t in lesson["tags"])
    fm.append("links_to:")
    fm.extend(f"  - {json.dumps(link)}" for link in related)
    fm.append("---")

    body: list[str] = [f"# {lesson['id']}", "", _GENERATED_BANNER, ""]
    body += ["## Lesson", "", lesson["lesson"], ""]
    if lesson["problem"]:
        body += ["## Problem", "", lesson["problem"], ""]
    if lesson["solution"]:
        body += ["## Solution", "", lesson["solution"], ""]
    if lesson["task"]:
        body += ["## Task", "", lesson["task"], ""]

    body += ["## Validation", ""]
    if lesson["validation"]:
        body += [f"- {v}" for v in lesson["validation"]]
    else:
        body.append("No validation text stored.")
    body.append("")

    body += ["## Context", ""]
    body.append(f"- Repo: `{repo}`")
    body.append(f"- Risk: `{lesson['risk']}`")
    body.append(f"- Source: `{lesson['source']}`")
    if lesson["stored_at"]:
        body.append(f"- Stored: `{lesson['stored_at']}`")
    if lesson["commands_used"]:
        body.append("- Commands: " + ", ".join(f"`{c}`" for c in lesson["commands_used"]))
    if lesson["files_touched"]:
        body.append("- Files: " + ", ".join(f"`{f}`" for f in lesson["files_touched"]))
    body.append("")

    body += ["## Related", ""]
    body += [f"- {link}" for link in related]
    body.append("")

    return "\n".join(fm) + "\n\n" + "\n".join(body).rstrip() + "\n"


def _lesson_line(lesson: dict[str, Any]) -> str:
    task = lesson["task"] or lesson["lesson"]
    label = task if len(task) <= 100 else task[:97] + "..."
    return f"- [[{LEARN_SUBDIR}/patterns/{lesson['id']}]] — {label}"


def _sorted_desc(lessons: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Newest first; ``id`` is the deterministic tiebreaker (ids are time-sortable)."""
    return sorted(lessons, key=lambda l: (l["stored_at"], l["id"]), reverse=True)


def build_learn_index(lessons: list[dict[str, Any]]) -> str:
    repos: dict[str, int] = {}
    for l in lessons:
        repos[l["repo"]] = repos.get(l["repo"], 0) + 1
    tag_groups = _group_by_tag(lessons)

    out = ["# Learn Index", "", _GENERATED_BANNER, "", "## Summary", ""]
    out.append(f"- Total lessons: {len(lessons)}")
    out.append("- Repos:")
    for repo in sorted(repos):
        out.append(f"  - [[{LEARN_SUBDIR}/repos/{_slug(repo)}]] ({repos[repo]})")
    out.append("- Tags:")
    for slug in sorted(tag_groups):
        out.append(f"  - [[{LEARN_SUBDIR}/tags/{slug}]] ({len(tag_groups[slug]['lessons'])})")
    out += ["", "## Latest lessons", ""]
    for l in _sorted_desc(lessons)[:10]:
        out.append(_lesson_line(l))
    out.append("")
    return "\n".join(out).rstrip() + "\n"


def build_repo_index(repo: str, lessons: list[dict[str, Any]]) -> str:
    out = [f"# Learn — {repo}", "", _GENERATED_BANNER, ""]
    out.append(f"{len(lessons)} lesson(s) for repo `{repo}`.")
    out.append("")
    for l in _sorted_desc(lessons):
        out.append(_lesson_line(l))
    out.append("")
    return "\n".join(out).rstrip() + "\n"


def build_tag_index(tag: str, lessons: list[dict[str, Any]]) -> str:
    out = [f"# Learn — #{tag}", "", _GENERATED_BANNER, ""]
    out.append(f"{len(lessons)} lesson(s) tagged `{tag}`.")
    out.append("")
    for l in _sorted_desc(lessons):
        out.append(_lesson_line(l))
    out.append("")
    return "\n".join(out).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Writing
# ---------------------------------------------------------------------------


def write_if_changed(path: Path, content: str, *, dry_run: bool) -> str:
    """Write ``content`` only when it differs. Returns 'created' | 'updated' | 'unchanged'."""
    existed = path.exists()
    if existed and path.read_text(encoding="utf-8") == content:
        return "unchanged"
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return "updated" if existed else "created"


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------


def export_lessons(vault_root: Path, lessons_path: Path, *, dry_run: bool = False) -> dict[str, Any]:
    """Run the full export. Returns a deterministic report dict."""
    raw_lessons, errors = load_lessons(lessons_path)

    normalized: list[dict[str, Any]] = []
    for raw in raw_lessons:
        lesson = normalize_lesson(raw)
        if not lesson["id"]:
            errors.append("skipped a record with no id")
            continue
        normalized.append(lesson)

    learn_root = vault_root / LEARN_SUBDIR
    counts: dict[str, int] = {
        "pattern_files_created": 0,
        "pattern_files_updated": 0,
        "pattern_files_unchanged": 0,
        "repo_indexes_written": 0,
        "tag_indexes_written": 0,
    }

    # Pattern notes.
    for lesson in normalized:
        path = learn_root / "patterns" / f"{_slug(lesson['id'])}.md"
        status = write_if_changed(path, render_lesson_markdown(lesson, vault_root), dry_run=dry_run)
        counts[f"pattern_files_{status}"] += 1

    # Repo indexes.
    by_repo: dict[str, list[dict[str, Any]]] = {}
    for l in normalized:
        by_repo.setdefault(l["repo"], []).append(l)
    for repo, items in sorted(by_repo.items()):
        path = learn_root / "repos" / f"{_slug(repo)}.md"
        if write_if_changed(path, build_repo_index(repo, items), dry_run=dry_run) != "unchanged":
            counts["repo_indexes_written"] += 1

    # Tag indexes (case-insensitive grouping).
    for slug, group in sorted(_group_by_tag(normalized).items()):
        path = learn_root / "tags" / f"{slug}.md"
        content = build_tag_index(group["display"], group["lessons"])
        if write_if_changed(path, content, dry_run=dry_run) != "unchanged":
            counts["tag_indexes_written"] += 1

    # Landing index.
    idx_status = write_if_changed(learn_root / "index.md", build_learn_index(normalized), dry_run=dry_run)

    report: dict[str, Any] = {
        "dry_run": dry_run,
        "lessons_read": len(raw_lessons),
        "lessons_exported": len(normalized),
        **counts,
        "index_written": idx_status != "unchanged",
        "errors": errors,
    }
    return report


def main(argv: list[str] | None = None) -> int:
    repo_root = Path(__file__).resolve().parents[1]
    parser = argparse.ArgumentParser(description="Export curated learn records into an Obsidian vault.")
    parser.add_argument("--vault", type=Path, default=Path("/Users/mansys/mqobsidian"),
                        help="Obsidian vault root.")
    parser.add_argument("--lessons", type=Path,
                        default=repo_root / "learn_engine" / "memory" / "lessons.jsonl",
                        help="Path to lessons.jsonl (the curated store).")
    parser.add_argument("--dry-run", action="store_true",
                        help="Compute and report changes without writing any files.")
    args = parser.parse_args(argv)

    if not args.vault.exists():
        print(f"error: vault does not exist: {args.vault}", file=sys.stderr)
        return 2

    report = export_lessons(args.vault, args.lessons, dry_run=args.dry_run)
    print(json.dumps(report, ensure_ascii=False, indent=2))
    return 1 if report["errors"] else 0


if __name__ == "__main__":
    raise SystemExit(main())
